name: sfb-book
channels:
  - defaults
dependencies:
  - pip
  - astropy=4.2
  - matplotlib=3.3
  - numpy=1.19
  - scikit-learn=0.24
  - jupyter
  - notebook
  - conda-forge::ctapipe=0.10.4
  - conda-forge::eventio
  - conda-forge::corsikaio
