name: sfb-book
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=4.2
  - corsikaio
  - ctapipe=0.10.5
  - eventio
  - numdifftools
  - jupyter
  - matplotlib=3.3
  - notebook
  - numpy=1.19
  - pandas=1.2
  - pip
  - scikit-learn=0.24
  - scipy=1.6
  - pip:
    - pyfact==0.26.1
